# Generated by Django 5.1.5 on 2025-03-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_remove_itinerary_itinerary_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='duration',
        ),
    ]
