# Generated by Django 5.1.5 on 2025-03-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_remove_itinerary_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='itinerary_data',
            field=models.JSONField(default='No data is available right now'),
            preserve_default=False,
        ),
    ]
